### PR TITLE
Remote keyboard from ssh console

### PR DESCRIPTION
**Pull request by Swiftb0y**
This adds outhid and duckhid to the terminal when USE_HID is true as suggested in #83

### CODE REVIEW

**Comment by Swiftb0y** [comment]
sorry I've run into some issues I have to debug further. I will PR tomorrow again

**Comment by Swiftb0y** [comment]
should work now. Maybe not the cleanest approach but it works pretty much as it is supposed to. 
The only thing that could be improved is something better than using cat in the _multi variants so you can navigate with the arrow keys

**Comment by Swiftb0y** [comment]
Sure. The only feature I'd like to add would be the ability to navigate with the arrow keys like in nano in the _multi variants.

**Comment by mame82** [comment]
`outhid`, `duckhid` and `outmouse` are available to login shell on latest commit, have to test how to incorporate these derivates into current code.

**Comment by Swiftb0y** [comment]
Cool, they'll be pretty useful.

**Comment by mame82** [comment]
But you have to reinstall, or at least run install.sh again, otherwise permissions for the HID files don't get fixed

**Pull request closed without merging**
