### PR TITLE
Quick FAQ update to account for the wifi client feature.

### PR DESCRIPTION
**Pull request by Swiftb0y**

### CODE REVIEW

**Comment by mame82** [comment]
Thanks for the addition

**Comment by mame82** [comment]
Merged to fast : ethernet connectivity = Internet connectivity

**Comment by Swiftb0y** [comment]
xD sorry

**Comment by Swiftb0y** [comment]
I would be glad to assist writing wiki entrys If you dont have time. 
I promise I will proofread my entrys more than once. :D

**Comment by mame82** [comment]
Indeed I'm short on time, everything is still under development and attention is growing. So missing docs are starting to get a problem.

If you'd like to help with this, you're welcome.

But be warned, one reason for having only bare docs is that I change things frequently.
Anyway, looking back to the latest commits, there have been more additions than changes

**Comment by Swiftb0y** [comment]
I'm still 16, so I've got enough time on my hands. What topics would be the most urgent/important ones?

**Comment by mame82** [comment]
No problem. Age doesn't matter, but quality should.a

A bunch of (closed) issues contain common questions, most of them already answered.

In my opinion it would be a gut start, to include them into the FAQ.

At some point I started labeling answered question, which could be interesting for other users, as `informative`.

Your questions about "settings priority" are a good example, but everything has to be rephrased  (clear, as short and precise as possible).

**Comment by Swiftb0y** [comment]
ok, Ill try my best. 
And I was just saying that I am 16 and english isn't my native language so don't except the worlds best phrasing.

**Comment by jcstill** [comment]
@Swiftb0y I could also proofread and help with phrasing if you want. And it seems to me like there is a need for an FAQ or Wiki.
-J

**Comment by Swiftb0y** [comment]
@jcstill that would be really nice of you. 
@mame82 I dont think just straight adding everything to the FAQ isnt a good idea. I would put everything either into a seperate wiki folder or use the github wiki feature.

**Pull request merged**
