### PR TITLE
Allow connecting to existing AP

### PR DESCRIPTION
**Pull request by Swiftb0y**
This is a little addon that uses wpa_supplicant to connect to already existing APs for greater range, more flexibility and more importantly ethernet access.
Sadly I don't know how to share this connection with the victim pc and every guide I tried to follow failed at `sudo iptables -t filter -A POSTROUTING -o usb0 -j MASQUERADE
iptables: No chain/target/match by that name.`

### CODE REVIEW

**Comment by mame82** [comment]
@Swiftb0y 
Hi,

I like the idea of fail over from WiFi client mode to AP mode.
Storing already used WiFi creds is a good idea, too.

Now for the things I'd like to change:
- The UMS image resize should be optional, with selectable size.
- There's no need to start the AP upfront before connecting to an existing WiFi (dnsmasq and hostapd don't have to be used in that case).
- Status of dd could be fetched with SIGUSR1.

So I suggest to point the PR to a new branch, which I can use for testing and refining.
Considering the UMS image, I thought about a dedicated configuration tool, which could be launched via SSH. The UMS image creation doesn't necessarily need to be run on installer and to have multiple images is a good idea, I guess. But I'd like to use your code as starting point.

**Comment by mame82** [comment]
Satus update: Started working on WiFi client part of this PR

**Comment by Swiftb0y** [comment]
ok. My interests have shifted a bit recently so I'm not actively working on a feature, but if you have a simple task I could do, I'd be happy to work on it.

**Comment by mame82** [comment]
I reworked your whole PR, but merged in before to credit your work.
Thanks for your effort, initial WiFi client capability is now present (only WPA2 PSK).

Example payload is here: https://github.com/mame82/P4wnP1/blob/master/payloads/wifi_connect.txt

**Comment by Swiftb0y** [comment]
Thanks. The next step would be to forward/route the traffic from the usbinterfaces to the wifi interface. The only solution I found was to use IPtables to forward the traffic but as already mentioned, that fails for some reason.
If there is anything simple I can do, let me know. I would like to work more on this project but I don't know what I could do.

Also, you forgot to remove this in setup.cfg
`# ===============================
# connect to normal wpa2 network
# ===============================

EXISTING_AP=false
EXISTING_AP_NAME=""
EXISTING_AP_PSK="" #not needed when entry already present in wpa_supplicant.conf (use wifi/append_secure_wpa_conf.sh to add entrys)
`

**Comment by mame82** [comment]
Thanks for pointing out, going to fix this tomorrow.

According forwarding:
Should be doable with two lines. Masquerading with iptables + ipv4 kernel routing.

Lets see if I can bring up an example the next days

**Pull request merged**
