### PR TITLE
Added rpi-update to apt-get install list to ensure it's available.

### PR DESCRIPTION
**Pull request by mikeflynn**
For whatever reason the Jessie image I used didn't have rpi-update installed so the command at the end of install failed. I just added it to the apt-get lists to ensure it's installed.

### CODE REVIEW

**Comment by mame82** [comment]
Thanks for your contribution, but Raspbian versions capable of running P4wnP1 always ship with rpi-update pre-installed.

I don't merge this in to avoid confusion with outdated raspbian.

**Comment by mikeflynn** [comment]
I can confirm that the Jessie image I had on file from late 2016 didn't have it and the install script failed until I installed it manually. Maybe everything from 2017 (and obviously Stretch) do, but it would not surprise me at all if other people have run in to this and it's trivial to add it to the apt-get list since it won't do anything if it's already installed.

**Comment by mame82** [comment]
> it's trivial to add it to the apt-get list since it won't do anything if it's already installed.

You're right on this, but the changes have to be ported to the new `install.sh` script.

**Comment by mikeflynn** [comment]
Yeah, I saw you just modified the install script and I'm happy to create a new PR based off the latest version. In fact I think it's just a one line change now that you don't have different apt-get installs for wifi vs non-wifi.

I admit I was using an old Jessie image I had already downloaded, I just thought the change was so simple that if it helped even one person it would be worth it.

**Comment by mame82** [comment]
>  I just thought the change was so simple that if it helped even one person it would be worth it.

I agree!

**Pull request closed without merging**
