### PR TITLE
Check if locked backdoor

### PR DESCRIPTION
**Pull request by Swiftb0y**
This has some screwed up commits again, so this not supposed to be merged. It should rather suggest an implementation for some basic payload branching. This would be the most useful when you need to check if the target computer is locked while not being able to look at the screen. A powershell snippet will be typed out that uses Wscript.Shell.SendKeys to send a *Lock-key and watchhidled.py is used to wait until the state changed. This could be typed out from the Lockscreen and succeed if the PC is unlocked and fail if it's locked.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
No comment?

**Comment by mame82** [comment]
Accidentally clossd before review, not able to reopen

**Comment by mame82** [comment]
Closed because experimental mouse branch has been deleted

**Comment by Swiftb0y** [comment]
Ohh ok. Should I PR it again to the master?

**Pull request closed without merging**
