### PR TITLE
Hidden SSID for Install.sh

### PR DESCRIPTION
**Pull request by jcstill**
This is a WIP for the #31 issue.
Look there for info on this.
The code I added works for changing the `ignore_broadcast_ssid` variable in `init_wifi.sh`.
However, I can't seem to actually hide the SSID....

Yes I have tried:
`ignore_broadcast_ssid=0`
`ignore_broadcast_ssid=1`
`ignore_broadcast_ssid=2`
All of which do not hide the network...

Will continue to work on this.
Any help would be greatly appreciated.
-J

### CODE REVIEW

**Comment by whackyhack** [comment]
How'd you determine that SSID isn't concealed?  My experience is that if your device has previously connected to this SSID (thus stores a "connection" to it), it has a tendency to display it in active scan even when ESS beacon isn't sent.  Try delete the stored connection from the device before scanning. (On iOS devices, deletion is called "Forget".)

**Comment by jcstill** [comment]
@whackyhack I deleted all the saved network settings on my laptop. However, when I get home from work later today I will check from my phone (which has never been connected to P4wnP1) and see if it shows up there.
Thanks and good catch.

**Comment by jcstill** [comment]
@whackyhack So I went ahead and added the 1 flag to the `ignore_broadcast_ssid` and checked on my phone and what do you know? It worked - SSID gone.

Also,
I'm starting to think that this might not be a good fix, reasoning is because you don't change any other settings from the install. What I mean is that for all of the settings, you go into the setup.cfg file and manually change them yourself.

Maybe on the first ssh and, of course, whenever you call it, you are presented with a menu screen similar to raspi-config and adjust _all_ the settings from there?
I think that may be better from a user's perspective. And that way everything is in one spot. Quick and easy access.
I might go ahead and create something like that.

@mame82 before I go ahead and do that though, I want to see if you already have something like that in development? I dont want to make it and then find out you already have one made. haha

**Comment by mame82** [comment]
> before I go ahead and do that though, I want to see if you already have something like that in development? I dont want to make it and then find out you already have one made. haha

I've implemented this on setup.cfg basis, here: 
https://github.com/mame82/P4wnP1/commit/02b1101ffd27020b6d413b176784075ed4c74f91

It uses `ignore_broadcast_ssid=2`, which worked out in my tests.
It should be noted that some clients, like Windows 10, give an hint on a network without name.
Anyway, the SSID has to be known to connect.

**Pull request closed without merging**
